### ISSUE TITLE
Bouncer status

### ISSUE THREAD

**Issue by mojo-jojo-7** [samruston/squigglyspans#2]
Hi @samruston, I was searching for a way to contact you but could not get an email anywhere, so I'm sorry for hijacking one of your public repos like this.

I've recently discovered that you've stopped development on Bouncer when I tried to install it on a new phone. I LOVED that app! Do you ever plan on reviving it? If not, perhaps, could you consider open sourcing it? I'm sure it will garner a passionate community behind it :)

Bouncer was a God send. It was a unique app that perfectly fulfilled a niche use case and I would love to be able to use it again. Thanks for your consideration!

**Comment by samruston** [comment]
Hi,

You should be able to install the app from the My Apps section of Google Play. Unfortunately I had to remove it from the Play Store because Google made some changes in Android 14 that make it incompatible with Bouncer on the Play Store. If you press the contact support button in the help section of Bouncer though I can send you a version that works with Android 14. No plans on open sourcing it right now.

If you need to contact me there should be a contact option in the apps, or the contact email should be available on my Play Store page
